repository:
  default_branch: main
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  allow_merge_commit: false 
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  # default GitHub labels to keep
  - name: duplicate
    description: This issue or pull request already exists
    color: 'cfd3d7'

  - name: invalid
    description: This doesn't seem right
    color: 'e4e669'

  - name: question
    description: Further information is requested
    color: 'd876e3'

  - name: wontfix
    description: This will not be worked on
    color: 'ffffff'

  # commit / issue types
  - name: bug
    new_name: bug/fix
    description: A bug or bug fix
    color: 'd73a4a'

  - name: build
    description: Changes that affect the build system or external dependencies
    color: 'D41E91'
    
  - name: chore
    description: A change that does not deal with the application code, nor fits into other ticket types
    color: '0B4491'

  - name: ci
    description: Changes to CI configuration files or scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
    color: '0D5C5D'

  - name: documentation
    new_name: docs
    description: Changes to documentation
    color: '666666'

  - name: enhancement
    new_name: feat
    description: A new feature
    color: '0052cc'
    
  - name: perf
    description: A code change that improves performance
    color: 'E6D835'

  - name: refactor
    description: A code change that neither fixes a bug nor adds a feature
    color: '5000A9'
    
  - name: style
    description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    color: '1EBCD4'

  - name: test
    description: Adding missing tests or correcting existing tests
    color: '2BF535'

branches:
  - name: main
    protection:
      # https://docs.github.com/en/rest/reference/repos#update-branch-protection
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
      allow_force_pushes: true
      allow_deletions: false
